version: '3'
services:
  PBR.ONE-Dev-Main:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/etc/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  PBR.ONE-Dev-Test:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./test:/etc/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  PBR.ONE-Dev-Web:
    image: nginx
    ports:
      - "8082:80"
    volumes:
      - ./web:/etc/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
